sudo: required

#docker engine v1.8 or later is required
#trusty is beta at 2015/10/29
dist: trusty

language: bash

services:
  - docker

before_install:
  - docker build -t oacis/oacis .
  - docker pull busybox

script:
  - bash test/test_all.sh

